[package]
name = "advent2019"
version = "0.1.0"
authors = ["Isaac Curtis <iicurtis@outlook.com>"]
edition = "2018"

[dependencies]
clap = "2"
itertools = "0.8"
hashbrown = "0.6"
rayon = "1"
# simdeez = "0.5"
#nom = "4"

[dev-dependencies]
criterion = "*"

[[bench]]
name = 'aoc'
harness = false
